/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/GWxYbTmuKGDyqbDX/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#c8cce8']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <mesh
            name="BG"
            geometry={nodes.BG.geometry}
            material={materials['']}
            receiveShadow
            rotation={[0, -Math.PI / 2, 0]}
          />
          <group name="Scene" position={[40, 76.27, 54.1]} rotation={[0.03, 0.79, 0]} scale={1.38}>
            <mesh
              name="Cylinder 6"
              geometry={nodes['Cylinder 6'].geometry}
              material={materials['Walls 2']}
              castShadow
              receiveShadow
              position={[-38.63, -241.84, 220.69]}
            />
            <mesh
              name="Cylinder 5"
              geometry={nodes['Cylinder 5'].geometry}
              material={materials.Walls}
              castShadow
              receiveShadow
              position={[-136.05, -241.84, 220.69]}
            />
            <group name="Pencil Holder" position={[140.72, -128.13, 12.98]}>
              <mesh
                name="Cylinder 4"
                geometry={nodes['Cylinder 4'].geometry}
                material={materials['Cylinder 4 Material']}
                castShadow
                receiveShadow
                position={[-1.22, 2.66, 1.26]}
                rotation={[0.31, 0.05, 0.17]}
                scale={1}
              />
              <mesh
                name="Cylinder 3"
                geometry={nodes['Cylinder 3'].geometry}
                material={materials['Cylinder 3 Material']}
                castShadow
                receiveShadow
                position={[-1.13, 2.17, -2.92]}
                rotation={[-0.12, -0.02, 0.17]}
                scale={1}
              />
              <mesh
                name="Cylinder 2"
                geometry={nodes['Cylinder 2'].geometry}
                material={materials['Cylinder 2 Material']}
                castShadow
                receiveShadow
                position={[2.87, 3.17, -0.92]}
                rotation={[0, 0, -0.17]}
              />
              <mesh
                name="Cylinder"
                geometry={nodes.Cylinder.geometry}
                material={materials['Plant Pot']}
                castShadow
                receiveShadow
                position={[0, -4.2, 0]}
              />
            </group>
            <group name="Paper" position={[109.6, -138.08, 21.02]}>
              <mesh
                name="Rectangle 14"
                geometry={nodes['Rectangle 14'].geometry}
                material={materials['Rectangle 14 Material']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[-Math.PI / 2, 0, -0.52]}
                scale={1}
              />
            </group>
            <mesh
              name="Rectangle 13"
              geometry={nodes['Rectangle 13'].geometry}
              material={materials['Rectangle 13 Material']}
              castShadow
              receiveShadow
              position={[115.52, -122.93, -74.29]}
              rotation={[-Math.PI / 2, -0.26, 0]}
              scale={1}
            />
            <group name="Drawing Surface" position={[116.51, -127.07, -74.6]}>
              <mesh
                name="Cube 3"
                geometry={nodes['Cube 3'].geometry}
                material={materials['Cube 3 Material']}
                castShadow
                receiveShadow
                position={[18.35, -1.68, -59.54]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[0.28, 0.79, 1]}
              />
              <mesh
                name="Cube 2"
                geometry={nodes['Cube 2'].geometry}
                material={materials['Cube 2 Material']}
                castShadow
                receiveShadow
                position={[18.35, -1.68, 61.3]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[0.28, 0.79, 1]}
              />
              <mesh
                name="Cube 31"
                geometry={nodes['Cube 31'].geometry}
                material={materials['Cube 31 Material']}
                castShadow
                receiveShadow
                position={[0.96, -9.46, -59.54]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.77, 1, 1]}
              />
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials['Cube Material']}
                castShadow
                receiveShadow
                position={[0.96, -9.46, 61.3]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.77, 1, 1]}
              />
              <mesh
                name="Rectangle 131"
                geometry={nodes['Rectangle 131'].geometry}
                material={materials['Rectangle 131 Material']}
                castShadow
                receiveShadow
                position={[0.39, 0.25, 0]}
                rotation={[-Math.PI / 2, -0.26, 0]}
                scale={1}
              />
            </group>
            <group name="Painting Rotation" position={[-120.24, -143.78, -154.97]} rotation={[0, 1.18, 0]} scale={1}>
              <group name="Painting" position={[0, 0, 0]} rotation={[0, 0, -0.17]}>
                <mesh
                  name="Cube 6"
                  geometry={nodes['Cube 6'].geometry}
                  material={materials['Cube 6 Material']}
                  castShadow
                  receiveShadow
                  position={[-16.08, 37.93, 1.12]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.48, 10.92, 12.88]}
                />
                <mesh
                  name="Cube 5"
                  geometry={nodes['Cube 5'].geometry}
                  material={materials['Painting Legs']}
                  castShadow
                  receiveShadow
                  position={[-16.08, -11.37, 1.12]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[1, 10.92, 1]}
                />
                <mesh
                  name="Cube 4"
                  geometry={nodes['Cube 4'].geometry}
                  material={materials['Painting Legs']}
                  castShadow
                  receiveShadow
                  position={[-8.31, -12.24, 21.45]}
                  rotation={[-0.17, 0, 0]}
                  scale={[1, 23.65, 1]}
                />
                <mesh
                  name="Cube 7"
                  geometry={nodes['Cube 7'].geometry}
                  material={materials['Painting Legs']}
                  castShadow
                  receiveShadow
                  position={[11.27, -6.77, 0.2]}
                  rotation={[0, 0, 0.3]}
                  scale={[1, 23.52, 1]}
                />
                <mesh
                  name="Cube 32"
                  geometry={nodes['Cube 32'].geometry}
                  material={materials['Painting Legs']}
                  castShadow
                  receiveShadow
                  position={[-8.31, -12.24, -21.45]}
                  rotation={[0.17, 0, 0]}
                  scale={[1, 23.65, 1]}
                />
              </group>
            </group>
            <group name="Lamp" position={[91.93, -112.97, -186.02]}>
              <mesh
                name="Cylinder 31"
                geometry={nodes['Cylinder 31'].geometry}
                material={materials['Cylinder 31 Material']}
                castShadow
                receiveShadow
                position={[0, 10.84, 0]}
                scale={[1, 3.09, 1]}
              />
              <mesh
                name="Cylinder 21"
                geometry={nodes['Cylinder 21'].geometry}
                material={materials['Cylinder 21 Material']}
                castShadow
                receiveShadow
                position={[0, -12.65, 0]}
                scale={[1, 12.72, 1]}
              />
              <mesh
                name="Cylinder1"
                geometry={nodes.Cylinder1.geometry}
                material={materials['Cylinder1 Material']}
                castShadow
                receiveShadow
                position={[0, -24.65, 0]}
                scale={[1, 0.34, 1]}
              />
            </group>
            <group name="Chair" position={[-2.73, -188.56, -36.11]} scale={[1, 0.9, 1]}>
              <mesh
                name="Cube 51"
                geometry={nodes['Cube 51'].geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[-16.92, -4.55, 15.9]}
                rotation={[-1.63, 0.06, -2.35]}
                scale={1}
              />
              <mesh
                name="Cube 41"
                geometry={nodes['Cube 41'].geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[16.13, -4.55, 15.9]}
                rotation={[-1.63, -0.06, -0.79]}
                scale={1}
              />
              <mesh
                name="Cube 52"
                geometry={nodes['Cube 52'].geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[16.13, -4.55, -17.15]}
                rotation={[-1.51, -0.06, -2.35]}
              />
              <mesh
                name="Cube 33"
                geometry={nodes['Cube 33'].geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[-16.92, -4.55, -17.15]}
                rotation={[-1.51, 0.06, -0.79]}
                scale={1}
              />
              <mesh
                name="Cylinder2"
                geometry={nodes.Cylinder2.geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[0, 33.81, 0]}
              />
            </group>
            <group name="Books" position={[141.35, -118.78, -170.13]}>
              <mesh
                name="Cube 53"
                geometry={nodes['Cube 53'].geometry}
                material={materials.Books}
                castShadow
                receiveShadow
                position={[4.58, 0, 0]}
                rotation={[-Math.PI / 2, -1.36, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Cube 61"
                geometry={nodes['Cube 61'].geometry}
                material={materials.Books}
                castShadow
                receiveShadow
                position={[-9.19, -5.95, 0]}
                rotation={[-Math.PI / 2, -0.99, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Cube 42"
                geometry={nodes['Cube 42'].geometry}
                material={materials.Books}
                castShadow
                receiveShadow
                position={[16.63, 0, 0]}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials['Sphere Material']}
              castShadow
              receiveShadow
              position={[10.34, -199.79, -196.77]}
            />
            <group name="Decoration" position={[169.61, -28.77, -129.1]}>
              <mesh
                name="Rectangle 10"
                geometry={nodes['Rectangle 10'].geometry}
                material={materials['Rectangle 10 Material']}
                castShadow
                receiveShadow
                position={[-5.29, 4, -22.78]}
                rotation={[0, -Math.PI / 2, 0]}
              />
              <mesh
                name="Rectangle 9"
                geometry={nodes['Rectangle 9'].geometry}
                material={materials['Rectangle 9 Material']}
                castShadow
                receiveShadow
                position={[-0.51, 5.85, 19.92]}
                rotation={[0, -Math.PI / 2, 0]}
              />
              <mesh
                name="Rectangle 8"
                geometry={nodes['Rectangle 8'].geometry}
                material={materials['Rectangle 8 Material']}
                castShadow
                receiveShadow
                position={[7.39, 0, 0]}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
            <mesh
              name="Rectangle 11"
              geometry={nodes['Rectangle 11'].geometry}
              material={materials['Rectangle 11 Material']}
              castShadow
              receiveShadow
              position={[178.75, -27.98, 41.1]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 7"
              geometry={nodes['Rectangle 7'].geometry}
              material={materials.Frame}
              castShadow
              receiveShadow
              position={[182.17, -27.98, 41.1]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <group name="Painting1" position={[134.99, -23.36, -226.96]} scale={0.68}>
              <mesh
                name="Rectangle 141"
                geometry={nodes['Rectangle 141'].geometry}
                material={materials['Rectangle 141 Material']}
                castShadow
                receiveShadow
                position={[0, 0, 0.1]}
                scale={[0.88, 1.02, 1]}
              />
              <mesh
                name="Rectangle 142"
                geometry={nodes['Rectangle 142'].geometry}
                material={materials.Frame}
                castShadow
                receiveShadow
                position={[0, 0, -3.15]}
              />
            </group>
            <mesh
              name="Rectangle 12"
              geometry={nodes['Rectangle 12'].geometry}
              material={materials['Rectangle 12 Material']}
              castShadow
              receiveShadow
              position={[-129.5, -27.24, -229.45]}
              scale={[1, 1.14, 1]}
            />
            <mesh
              name="Rectangle 6"
              geometry={nodes['Rectangle 6'].geometry}
              material={materials.Frame}
              castShadow
              receiveShadow
              position={[-129.5, -27.24, -231.1]}
            />
            <group name="Window" position={[7, -36.54, -232.82]}>
              <mesh
                name="Cube 34"
                geometry={nodes['Cube 34'].geometry}
                material={materials.Frame}
                castShadow
                receiveShadow
                position={[0, -26.02, 2.23]}
              />
              <mesh
                name="Rectangle 5"
                geometry={nodes['Rectangle 5'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0.5, -0.04, 1.03]}
              />
              <mesh
                name="Plane"
                geometry={nodes.Plane.geometry}
                material={materials.Frame}
                castShadow
                receiveShadow
                position={[0, 0, 1.71]}
              />
            </group>
            <group name="Boxes" position={[105.63, -199.76, -106.69]}>
              <mesh
                name="Cube 21"
                geometry={nodes['Cube 21'].geometry}
                material={materials.Boxes}
                castShadow
                receiveShadow
                position={[15.28, -8.21, 69.38]}
                rotation={[0, -0.23, 0]}
              />
              <mesh
                name="Cube1"
                geometry={nodes.Cube1.geometry}
                material={materials.Boxes}
                castShadow
                receiveShadow
                position={[0, 0, -51.52]}
                rotation={[0, 0.38, 0]}
              />
            </group>
            <group name="Carpet" position={[-66.88, -225.76, -34.38]}>
              <mesh
                name="Ellipse 3"
                geometry={nodes['Ellipse 3'].geometry}
                material={materials['Ellipse 3 Material']}
                castShadow
                receiveShadow
                position={[0, 0.32, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Ellipse"
                geometry={nodes.Ellipse.geometry}
                material={materials['Ellipse Material']}
                castShadow
                receiveShadow
                position={[0, -0.32, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="Plant" position={[83.69, -174.32, 99.33]} scale={0.87}>
              <mesh
                name="Cube 43"
                geometry={nodes['Cube 43'].geometry}
                material={materials.Plant}
                castShadow
                receiveShadow
                position={[-3.36, -2.56, 11.3]}
                rotation={[0, 1.42, 0]}
                scale={[1.09, 1.09, 0.91]}
              />
              <mesh
                name="Cube 54"
                geometry={nodes['Cube 54'].geometry}
                material={materials.Plant}
                castShadow
                receiveShadow
                position={[-8.1, -2.56, -1.21]}
                rotation={[0, -0.08, 0]}
                scale={[1.09, 1.09, 0.73]}
              />
              <mesh
                name="Cube 35"
                geometry={nodes['Cube 35'].geometry}
                material={materials.Plant}
                castShadow
                receiveShadow
                position={[-14.73, -2.56, -9.47]}
                rotation={[0, -0.47, 0]}
                scale={[1.09, 1.09, 0.73]}
              />
              <mesh
                name="Cube 22"
                geometry={nodes['Cube 22'].geometry}
                material={materials.Plant}
                castShadow
                receiveShadow
                position={[12.9, -2.56, -4.67]}
                rotation={[-Math.PI, -0.17, -Math.PI]}
                scale={[1.09, 1.09, 0.82]}
              />
              <mesh
                name="Cube2"
                geometry={nodes.Cube2.geometry}
                material={materials.Plant}
                castShadow
                receiveShadow
                position={[-0.37, -2.56, -20.64]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={1.09}
              />
              <mesh
                name="Ellipse1"
                geometry={nodes.Ellipse1.geometry}
                material={materials['Painting Legs']}
                castShadow
                receiveShadow
                position={[-2.66, -3.09, -5.18]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Cylinder 61"
                geometry={nodes['Cylinder 61'].geometry}
                material={materials['Plant Pot']}
                castShadow
                receiveShadow
                position={[-278.32, -43.76, -327.57]}
              />
              <mesh
                name="Cylinder 51"
                geometry={nodes['Cylinder 51'].geometry}
                material={materials['Plant Pot']}
                castShadow
                receiveShadow
                position={[-2.16, -26.12, -5.3]}
              />
            </group>
            <group name="Table" position={[117.88, -183.59, -99.35]}>
              <mesh
                name="Cylinder 41"
                geometry={nodes['Cylinder 41'].geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[43.06, -2.31, 129.92]}
              />
              <mesh
                name="Cylinder 32"
                geometry={nodes['Cylinder 32'].geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[43.06, -2.31, -115.14]}
              />
              <mesh
                name="Cylinder 42"
                geometry={nodes['Cylinder 42'].geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[-41.17, -2.31, 129.92]}
              />
              <mesh
                name="Cylinder 22"
                geometry={nodes['Cylinder 22'].geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[-41.17, -2.31, -115.14]}
              />
              <mesh
                name="Rectangle 4"
                geometry={nodes['Rectangle 4'].geometry}
                material={materials.Table}
                castShadow
                receiveShadow
                position={[0, 31.81, 12.06]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <directionalLight
              name="Directional Light"
              castShadow
              intensity={0.7}
              shadow-mapSize-width={1024}
              shadow-mapSize-height={1024}
              shadow-camera-near={-10000}
              shadow-camera-far={100000}
              shadow-camera-left={-1000}
              shadow-camera-right={1000}
              shadow-camera-top={1000}
              shadow-camera-bottom={-1000}
              position={[-134.04, 250.92, -44.2]}
            />
            <group name="Walls and Floor" position={[0, -71.58, -54.1]}>
              <mesh
                name="Floor"
                geometry={nodes.Floor.geometry}
                material={materials['Floor Material']}
                castShadow
                receiveShadow
                position={[0, -177.5, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Wall1"
                geometry={nodes.Wall1.geometry}
                material={materials['Wall1 Material']}
                castShadow
                receiveShadow
                position={[200, 2.5, 0]}
                rotation={[0, -Math.PI / 2, 0]}
              />
              <mesh
                name="Wall2"
                geometry={nodes.Wall2.geometry}
                material={materials['Wall2 Material']}
                castShadow
                receiveShadow
                position={[0, 2.5, -200]}
              />
            </group>
          </group>
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
