/*
  Auto-generated by Spline
*/
import React, { useEffect, useState, useRef } from 'react';
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'


export default function ToonRoom({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/97An8Hnry0xSWlro/scene.splinecode')

  const sceneRef = useRef();

  const [mousePosition, setMousePosition] = useState({x: 0, y: 0});

  useEffect(() => {
    const handleMouseMove = (event) => {
      setMousePosition({
        x: (event.clientX / window.innerWidth) * 2 - 1,
        y: -(event.clientY / window.innerHeight) * 2 + 1,
      });
    };

    window.addEventListener('mousemove', handleMouseMove);

    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
    };
   }, []);

   useEffect(() => {
    if (sceneRef.current) {
      const { x, y } = mousePosition;

      // Apply a small rotation based on mouse position
      // You might need to adjust the factor to control the rotation sensitivity
      sceneRef.current.rotation.y = x * 0.1;
      sceneRef.current.rotation.x = y * 0.1;
    }
  }, [mousePosition]);


  return (
    <>
      {/* <color attach="background" args={['#5e5e5e']} /> */}
      <color attach="background" args={['white']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <group
            name="Dumbbell 2"
            position={[-155.12, -157.17, -21.25]}
            rotation={[0, -0.26, -Math.PI / 2]}
            scale={0.79}
          >
            <mesh
              name="Ellipse"
              geometry={nodes.Ellipse.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[0, 27.46, 0]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={0.38}
            />
            <mesh
              name="Ellipse1"
              geometry={nodes.Ellipse1.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[0, -14.67, 0]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={0.38}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials['BackPack White']}
              castShadow
              receiveShadow
              position={[0.33, -0.78, 0.13]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.38, 0.04, 0.38]}
            />
          </group>
          <group name="Dumbbell" position={[-154.61, -155.28, -74.97]} scale={0.79}>
            <mesh
              name="Ellipse2"
              geometry={nodes.Ellipse2.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[0, 27.46, 0]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={0.38}
            />
            <mesh
              name="Ellipse3"
              geometry={nodes.Ellipse3.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[0, -14.67, 0]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={0.38}
            />
            <mesh
              name="Cylinder1"
              geometry={nodes.Cylinder1.geometry}
              material={materials['BackPack White']}
              castShadow
              receiveShadow
              position={[0.33, -0.78, 0.13]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.38, 0.04, 0.38]}
            />
          </group>
          <group name="Barbell 2" position={[2.69, 77.49, -144.15]} scale={[-0.19, 0.19, 0.19]}>
            <mesh
              name="Ellipse 3"
              geometry={nodes['Ellipse 3'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-199.63, 0, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Ellipse 2"
              geometry={nodes['Ellipse 2'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[207.1, 0, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Ellipse 31"
              geometry={nodes['Ellipse 31'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-235.24, 0, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Ellipse4"
              geometry={nodes.Ellipse4.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[171.49, 0, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Cylinder2"
              geometry={nodes.Cylinder2.geometry}
              material={materials['BackPack White']}
              castShadow
              receiveShadow
              position={[0, 0.86, 0.34]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[1, 1.15, 1]}
            />
          </group>
          <group name="BarbellRack 2" position={[2.24, 63.58, -147.1]} scale={[-0.19, 0.19, 0.19]}>
            <mesh
              name="Boolean 2"
              geometry={nodes['Boolean 2'].geometry}
              material={nodes['Boolean 2'].material}
              castShadow
              receiveShadow
              position={[-151.11, 0, -1.82]}
            />
            <mesh
              name="Boolean"
              geometry={nodes.Boolean.geometry}
              material={nodes.Boolean.material}
              castShadow
              receiveShadow
              position={[151.11, 0, -1.82]}
            />
          </group>
          <group name="Backpack" position={[-80.39, -142.89, 17.5]} scale={0.31}>
            <mesh
              name="Boolean1"
              geometry={nodes.Boolean1.geometry}
              material={nodes.Boolean1.material}
              castShadow
              receiveShadow
              position={[14.3, -3.49, -8.62]}
            />
            <mesh
              name="TopRing"
              geometry={nodes.TopRing.geometry}
              material={materials.BackPack}
              castShadow
              receiveShadow
              position={[17.8, 90.34, -19.16]}
              rotation={[-0.39, 0, 0]}
              scale={[1, 1.5, 1]}
            />
            <mesh
              name="WaterBottleLid"
              geometry={nodes.WaterBottleLid.geometry}
              material={materials.Painting}
              castShadow
              receiveShadow
              position={[-84.15, 15.04, 16.63]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.14, 0.73, 0.33]}
            />
            <mesh
              name="WaterBottle"
              geometry={nodes.WaterBottle.geometry}
              material={materials.WallsTopToon}
              castShadow
              receiveShadow
              position={[-84.15, -19.97, 16.63]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.22, 0.73, 0.5]}
            />
            <mesh
              name="FrontPouchZipper"
              geometry={nodes.FrontPouchZipper.geometry}
              material={materials.BackPack}
              castShadow
              receiveShadow
              position={[14.3, 2.47, 71.32]}
              scale={[0.56, 0.1, 0.74]}
            />
            <mesh
              name="FrontPouch"
              geometry={nodes.FrontPouch.geometry}
              material={materials['BackPack White']}
              castShadow
              receiveShadow
              position={[14.3, -27.57, 68.17]}
              scale={[0.69, 1, 0.74]}
            />
            <mesh
              name="Zipper"
              geometry={nodes.Zipper.geometry}
              material={materials.MonitorScreenToon}
              castShadow
              receiveShadow
              position={[14.3, 4, 1.98]}
              scale={[0.99, 0.99, 0.11]}
            />
          </group>
          <pointLight
            name="Point Light"
            castShadow
            intensity={1.1}
            distance={741}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            position={[-428.4, -62.81, 452.75]}
          />
          <group name="WallLights" position={[173.35, 37.06, 74.28]}>
            <group name="Orb 13" position={[-5.59, -10.64, 155.03]} rotation={[-0.42, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light1"
                intensity={1.58}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -37.38, 5.33]}
              />
              <mesh
                name="Orb"
                geometry={nodes.Orb.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <group name="Orb 12" position={[-5.59, -10.64, -28.18]} rotation={[-0.42, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light2"
                intensity={0.8}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -37.38, 5.33]}
              />
              <mesh
                name="Orb1"
                geometry={nodes.Orb1.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <group name="Orb 131" position={[-5.59, -24.43, 115.76]} rotation={[-0.17, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light3"
                intensity={0.8}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -37.38, 5.33]}
              />
              <mesh
                name="Orb2"
                geometry={nodes.Orb2.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <group name="Orb 11" position={[-5.59, -24.43, -67.45]} rotation={[-0.17, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light4"
                intensity={0.8}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -37.38, 5.33]}
              />
              <mesh
                name="Orb3"
                geometry={nodes.Orb3.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <group name="Orb 132" position={[-5.59, -27.53, 77.99]} rotation={[0.11, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light5"
                intensity={0.8}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -37.38, 5.33]}
              />
              <mesh
                name="Orb4"
                geometry={nodes.Orb4.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <group name="Orb 10" position={[-5.59, -27.53, -105.22]} rotation={[0.11, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light6"
                intensity={0.8}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -37.38, 5.33]}
              />
              <mesh
                name="Orb5"
                geometry={nodes.Orb5.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <group name="Orb 133" position={[-5.59, -20.09, 42.92]} rotation={[0.33, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light7"
                intensity={0.8}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -37.38, 5.33]}
              />
              <mesh
                name="Orb6"
                geometry={nodes.Orb6.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <group name="Orb 9" position={[-5.59, -20.09, -140.29]} rotation={[0.33, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light8"
                intensity={0.8}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -37.38, 5.33]}
              />
              <mesh
                name="Orb7"
                geometry={nodes.Orb7.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <group name="Orb 134" position={[-5.59, -6.35, 14.06]} rotation={[0.47, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light9"
                intensity={0.8}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -37.38, 5.33]}
              />
              <mesh
                name="Orb8"
                geometry={nodes.Orb8.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <group name="Orb 8" position={[-5.59, -6.35, -169.15]} rotation={[0.47, 0, 0]} scale={0.09}>
              <pointLight
                name="Point Light10"
                intensity={0.8}
                distance={276}
                shadow-mapSize-width={4096}
                shadow-mapSize-height={4096}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#6795c5"
                position={[-0.37, -2.11, -16.67]}
              />
              <mesh
                name="Orb9"
                geometry={nodes.Orb9.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[0, 0.58, Math.PI / 2]}
                scale={1}
              />
            </group>
            <mesh
              name="Path 2"
              geometry={nodes['Path 2'].geometry}
              material={materials['Path 2 Material']}
              castShadow
              receiveShadow
              position={[-4.24, 11.8, -0.65]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Path"
              geometry={nodes.Path.geometry}
              material={materials['Path Material']}
              castShadow
              receiveShadow
              position={[-4.24, 11.8, -183.86]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <group name="WallHooks" position={[0.1, 20.71, 0]}>
              <mesh
                name="Torus 3"
                geometry={nodes['Torus 3'].geometry}
                material={materials.MonitorScreenToon}
                castShadow
                receiveShadow
                position={[0, 0, 183.63]}
                rotation={[0, 0, 1.57]}
              />
              <mesh
                name="Torus 2"
                geometry={nodes['Torus 2'].geometry}
                material={materials.MonitorScreenToon}
                castShadow
                receiveShadow
                position={[0, 0, -2.29]}
                rotation={[0, 0, 1.57]}
              />
              <mesh
                name="Torus"
                geometry={nodes.Torus.geometry}
                material={materials.MonitorScreenToon}
                castShadow
                receiveShadow
                position={[0, 0, -183.63]}
                rotation={[0, 0, 1.57]}
              />
            </group>
          </group>
          <group name="Gengar 2" position={[88.39, 66.19, -147.94]} rotation={[0, -0.04, 0]} scale={0.05}>
            <group name="Eyes" position={[-5.26, 136.26, 381.61]}>
              <mesh
                name="Sphere 2"
                geometry={nodes['Sphere 2'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[107.42, 0.21, 0]}
              />
              <mesh
                name="Sphere"
                geometry={nodes.Sphere.geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[-107.42, -0.21, 0]}
              />
            </group>
            <group name="BackSpikes" position={[17.3, 203.41, -104.07]}>
              <mesh
                name="Boolean2"
                geometry={nodes.Boolean2.geometry}
                material={nodes.Boolean2.material}
                castShadow
                receiveShadow
                position={[-17.3, -198.81, 65.8]}
              />
            </group>
          </group>
          <group name="Pencil Holder" position={[-202.56, -102.89, -144.88]} scale={1.3}>
            <mesh
              name="Cylinder 4"
              geometry={nodes['Cylinder 4'].geometry}
              material={materials.PillowToon}
              castShadow
              receiveShadow
              position={[-1.22, 2.66, 1.26]}
              rotation={[0.31, 0.05, 0.17]}
              scale={1}
            />
            <mesh
              name="Cylinder 3"
              geometry={nodes['Cylinder 3'].geometry}
              material={materials.BedMattressToon}
              castShadow
              receiveShadow
              position={[-1.13, 2.17, -2.92]}
              rotation={[-0.12, -0.02, 0.17]}
              scale={1}
            />
            <mesh
              name="Cylinder 2"
              geometry={nodes['Cylinder 2'].geometry}
              material={materials.SwitchBlueToon}
              castShadow
              receiveShadow
              position={[2.87, 3.17, -0.92]}
              rotation={[0, 0, -0.17]}
            />
            <mesh
              name="Cylinder3"
              geometry={nodes.Cylinder3.geometry}
              material={materials.Cup}
              castShadow
              receiveShadow
              position={[0, -4.2, 0]}
            />
          </group>
          <group name="Ditto" position={[35.93, -91.69, -84.55]} rotation={[0, 1, 0]}>
            <mesh
              name="Sphere 21"
              geometry={nodes['Sphere 21'].geometry}
              material={materials.BlackToon}
              castShadow
              receiveShadow
              position={[-16.24, 18.11, 7.22]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={1.2}
            />
            <mesh
              name="Sphere1"
              geometry={nodes.Sphere1.geometry}
              material={materials.BlackToon}
              castShadow
              receiveShadow
              position={[-16.51, 18.11, -9.75]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={1.2}
            />
            <mesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials.Ditto}
              castShadow
              receiveShadow
              position={[-0.64, 0.39, -2.26]}
            />
          </group>
          <group name="Lamp" position={[-146.93, -88.3, -149.94]}>
            <pointLight
              name="Point Light11"
              castShadow
              intensity={0.96}
              distance={408}
              shadow-mapSize-width={1024}
              shadow-mapSize-height={1024}
              shadow-camera-near={100}
              shadow-camera-far={100000}
              position={[0.39, 3.01, 3.71]}
            />
            <mesh
              name="Cylinder 31"
              geometry={nodes['Cylinder 31'].geometry}
              material={materials.Lamp}
              castShadow
              receiveShadow
              position={[0, 10.84, 0]}
              scale={[1, 3.09, 1]}
            />
            <mesh
              name="Boolean3"
              geometry={nodes.Boolean3.geometry}
              material={nodes.Boolean3.material}
              castShadow
              receiveShadow
              position={[0, -13.92, 0]}
            />
          </group>
          <group name="Plant" position={[-268.56, -138.47, -140.87]} scale={0.66}>
            <mesh
              name="Cube 4"
              geometry={nodes['Cube 4'].geometry}
              material={materials.Leaf}
              castShadow
              receiveShadow
              position={[-3.36, -2.56, 11.3]}
              rotation={[0, 1.42, 0]}
              scale={[1.09, 1.09, 0.91]}
            />
            <mesh
              name="Cube 5"
              geometry={nodes['Cube 5'].geometry}
              material={materials.Leaf}
              castShadow
              receiveShadow
              position={[-8.1, -2.56, -1.21]}
              rotation={[0, -0.08, 0]}
              scale={[1.09, 1.09, 0.73]}
            />
            <mesh
              name="Cube 3"
              geometry={nodes['Cube 3'].geometry}
              material={materials.Leaf}
              castShadow
              receiveShadow
              position={[-14.73, -2.56, -9.47]}
              rotation={[0, -0.47, 0]}
              scale={[1.09, 1.09, 0.73]}
            />
            <mesh
              name="Cube 2"
              geometry={nodes['Cube 2'].geometry}
              material={materials.Leaf}
              castShadow
              receiveShadow
              position={[12.9, -2.56, -4.67]}
              rotation={[-Math.PI, -0.17, -Math.PI]}
              scale={[1.09, 1.09, 0.82]}
            />
            <mesh
              name="Cube1"
              geometry={nodes.Cube1.geometry}
              material={materials.Leaf}
              castShadow
              receiveShadow
              position={[-0.37, -2.56, -20.64]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={1.09}
            />
            <mesh
              name="Ellipse5"
              geometry={nodes.Ellipse5.geometry}
              material={materials['Ellipse5 Material']}
              castShadow
              receiveShadow
              position={[-2.66, -3.09, -5.18]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cylinder 5"
              geometry={nodes['Cylinder 5'].geometry}
              material={materials.Pot}
              castShadow
              receiveShadow
              position={[-2.16, -26.12, -5.3]}
            />
          </group>
          <group name="RubixCube" position={[-117.08, 13.22, -149.82]} rotation={[0, Math.PI / 6, 0]} scale={0.13}>
            <mesh
              name="Cube 7"
              geometry={nodes['Cube 7'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[-51.18, 50.97, 51.38]}
            />
            <mesh
              name="Cube 6"
              geometry={nodes['Cube 6'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[-51.18, -0.12, 51.38]}
            />
            <mesh
              name="Cube 51"
              geometry={nodes['Cube 51'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[-51.18, -50.97, 51.38]}
            />
            <mesh
              name="Cube 71"
              geometry={nodes['Cube 71'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[-51.18, 50.97, -0.08]}
            />
            <mesh
              name="Cube 61"
              geometry={nodes['Cube 61'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[-51.18, -0.12, -0.08]}
            />
            <mesh
              name="Cube 41"
              geometry={nodes['Cube 41'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[-51.18, -50.97, -0.08]}
            />
            <mesh
              name="Cube 72"
              geometry={nodes['Cube 72'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[-51.18, 50.97, -51.38]}
            />
            <mesh
              name="Cube 62"
              geometry={nodes['Cube 62'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[-51.18, -0.12, -51.38]}
            />
            <mesh
              name="Cube 31"
              geometry={nodes['Cube 31'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[-51.18, -50.97, -51.38]}
            />
            <mesh
              name="Cube 73"
              geometry={nodes['Cube 73'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[0.14, 50.97, 51.38]}
            />
            <mesh
              name="Cube 63"
              geometry={nodes['Cube 63'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[0.14, -0.12, 51.38]}
            />
            <mesh
              name="Cube 52"
              geometry={nodes['Cube 52'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[0.14, -50.97, 51.38]}
            />
            <mesh
              name="Cube 74"
              geometry={nodes['Cube 74'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[0.14, 50.97, -0.08]}
            />
            <mesh
              name="Cube 64"
              geometry={nodes['Cube 64'].geometry}
              material={materials['Cube 64 Material']}
              castShadow
              receiveShadow
              position={[0.14, -0.12, -0.08]}
            />
            <mesh
              name="Cube 42"
              geometry={nodes['Cube 42'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[0.14, -50.97, -0.08]}
            />
            <mesh
              name="Cube 75"
              geometry={nodes['Cube 75'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[0.14, 50.97, -51.38]}
            />
            <mesh
              name="Cube 65"
              geometry={nodes['Cube 65'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[0.14, -0.12, -51.38]}
            />
            <mesh
              name="Cube 21"
              geometry={nodes['Cube 21'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[0.14, -50.97, -51.38]}
            />
            <mesh
              name="Cube 76"
              geometry={nodes['Cube 76'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[51.18, 50.97, 51.38]}
            />
            <mesh
              name="Cube 66"
              geometry={nodes['Cube 66'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[51.18, -0.12, 51.38]}
            />
            <mesh
              name="Cube 53"
              geometry={nodes['Cube 53'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[51.18, -50.97, 51.38]}
            />
            <mesh
              name="Cube 77"
              geometry={nodes['Cube 77'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[51.18, 50.97, -0.08]}
            />
            <mesh
              name="Cube 67"
              geometry={nodes['Cube 67'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[51.18, -0.12, -0.08]}
            />
            <mesh
              name="Cube 43"
              geometry={nodes['Cube 43'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[51.18, -50.97, -0.08]}
            />
            <mesh
              name="Cube 78"
              geometry={nodes['Cube 78'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[51.18, 50.97, -51.38]}
            />
            <mesh
              name="Cube 68"
              geometry={nodes['Cube 68'].geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[51.18, -0.12, -51.38]}
            />
            <mesh
              name="Cube2"
              geometry={nodes.Cube2.geometry}
              material={materials.RubixCubeToon}
              castShadow
              receiveShadow
              position={[51.18, -50.97, -51.38]}
            />
          </group>
          <group name="Keyboard" position={[85.42, -87.57, 178.32]} scale={[1.35, 0.73, 1.35]}>
            <mesh
              name="Cube3"
              geometry={nodes.Cube3.geometry}
              material={materials.Keyboard2Toon}
              castShadow
              receiveShadow
              position={[0, -0.98, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <group
              name="Keyboard Keys 2"
              position={[0.28, 2.18, -0.28]}
              rotation={[0, -0.01, 0]}
              scale={[0.28, 0.99, 0.28]}
            >
              <mesh
                name="Rectangle 20"
                geometry={nodes['Rectangle 20'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-11.82, -1.5, 100.94]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 19"
                geometry={nodes['Rectangle 19'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[12.95, -1.5, 98.75]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 18"
                geometry={nodes['Rectangle 18'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 109.27]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 17"
                geometry={nodes['Rectangle 17'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 84.67]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 16"
                geometry={nodes['Rectangle 16'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 60.2]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 15"
                geometry={nodes['Rectangle 15'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 36.69]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 14"
                geometry={nodes['Rectangle 14'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 12.26]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 13"
                geometry={nodes['Rectangle 13'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -12.35]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 12"
                geometry={nodes['Rectangle 12'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -36.86]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 11"
                geometry={nodes['Rectangle 11'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -61.09]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 10"
                geometry={nodes['Rectangle 10'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -85.6]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 4"
                geometry={nodes['Rectangle 4'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -110.06]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 33"
                geometry={nodes['Rectangle 33'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, 63.32]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 32"
                geometry={nodes['Rectangle 32'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, 38.59]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 31"
                geometry={nodes['Rectangle 31'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, 13.45]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 30"
                geometry={nodes['Rectangle 30'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -11.28]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 29"
                geometry={nodes['Rectangle 29'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -35.48]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 28"
                geometry={nodes['Rectangle 28'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -60.41]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 27"
                geometry={nodes['Rectangle 27'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -85.54]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 3"
                geometry={nodes['Rectangle 3'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -110.06]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 26"
                geometry={nodes['Rectangle 26'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, 68.23]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 25"
                geometry={nodes['Rectangle 25'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, 43.24]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 24"
                geometry={nodes['Rectangle 24'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, 18.65]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 23"
                geometry={nodes['Rectangle 23'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -5.71]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 22"
                geometry={nodes['Rectangle 22'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -30.13]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 21"
                geometry={nodes['Rectangle 21'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -54.25]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 6"
                geometry={nodes['Rectangle 6'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -78.6]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 2"
                geometry={nodes['Rectangle 2'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -106.75]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 7"
                geometry={nodes['Rectangle 7'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, 1.83]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 9"
                geometry={nodes['Rectangle 9'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, 106.1]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 8"
                geometry={nodes['Rectangle 8'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, 77.71]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 5"
                geometry={nodes['Rectangle 5'].geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, -73.34]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle"
                geometry={nodes.Rectangle.geometry}
                material={materials.Keyboard2Toon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, -103.7]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
          </group>
          <group name="Macbook" position={[100.55, -68.05, 59.6]} rotation={[0, 0.58, 0]} scale={0.23}>
            <group name="Keyboard Keys" position={[6.21, -76.05, 0.57]}>
              <mesh
                name="Rectangle 201"
                geometry={nodes['Rectangle 201'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-11.82, -1.5, 100.94]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 191"
                geometry={nodes['Rectangle 191'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[12.95, -1.5, 98.75]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 181"
                geometry={nodes['Rectangle 181'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 109.27]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 171"
                geometry={nodes['Rectangle 171'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 84.67]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 161"
                geometry={nodes['Rectangle 161'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 60.2]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 151"
                geometry={nodes['Rectangle 151'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 36.69]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 141"
                geometry={nodes['Rectangle 141'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, 12.26]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 131"
                geometry={nodes['Rectangle 131'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -12.35]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 121"
                geometry={nodes['Rectangle 121'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -36.86]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 111"
                geometry={nodes['Rectangle 111'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -61.09]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 101"
                geometry={nodes['Rectangle 101'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -85.6]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 41"
                geometry={nodes['Rectangle 41'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[37.46, -1.5, -110.06]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 331"
                geometry={nodes['Rectangle 331'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, 63.32]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 321"
                geometry={nodes['Rectangle 321'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, 38.59]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 311"
                geometry={nodes['Rectangle 311'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, 13.45]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 301"
                geometry={nodes['Rectangle 301'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -11.28]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 291"
                geometry={nodes['Rectangle 291'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -35.48]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 281"
                geometry={nodes['Rectangle 281'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -60.41]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 271"
                geometry={nodes['Rectangle 271'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -85.54]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 34"
                geometry={nodes['Rectangle 34'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[12.51, -1.5, -110.06]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 261"
                geometry={nodes['Rectangle 261'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, 68.23]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 251"
                geometry={nodes['Rectangle 251'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, 43.24]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 241"
                geometry={nodes['Rectangle 241'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, 18.65]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 231"
                geometry={nodes['Rectangle 231'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -5.71]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 221"
                geometry={nodes['Rectangle 221'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -30.13]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 211"
                geometry={nodes['Rectangle 211'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -54.25]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 61"
                geometry={nodes['Rectangle 61'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -78.6]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 210"
                geometry={nodes['Rectangle 210'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-12.55, -1.5, -106.75]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 71"
                geometry={nodes['Rectangle 71'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, 1.83]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 91"
                geometry={nodes['Rectangle 91'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, 106.1]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 81"
                geometry={nodes['Rectangle 81'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, 77.71]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle 51"
                geometry={nodes['Rectangle 51'].geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, -73.34]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Rectangle1"
                geometry={nodes.Rectangle1.geometry}
                material={materials.KeyboardCapToon}
                castShadow
                receiveShadow
                position={[-37.46, -1.5, -103.7]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <mesh
              name="Boolean 21"
              geometry={nodes['Boolean 21'].geometry}
              material={nodes['Boolean 21'].material}
              castShadow
              receiveShadow
              position={[0.63, 0.39, 0]}
            />
            <mesh
              name="Cube 32"
              geometry={nodes['Cube 32'].geometry}
              material={materials.MacbookScreenToon}
              castShadow
              receiveShadow
              position={[84.83, 6.77, 0]}
              rotation={[-Math.PI / 2, -1.4, -Math.PI / 2]}
              scale={[1.09, 1, 1]}
            />
          </group>
          <group name="Monitor" position={[137.04, -37.58, 175.42]} scale={0.36}>
            <mesh
              name="Boolean 22"
              geometry={nodes['Boolean 22'].geometry}
              material={nodes['Boolean 22'].material}
              castShadow
              receiveShadow
              position={[-0.63, 0, 0]}
            />
            <mesh
              name="Cube 69"
              geometry={nodes['Cube 69'].geometry}
              material={materials.MonitorScreenToon}
              castShadow
              receiveShadow
              position={[-38.54, 21.41, 0]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={[0.96, 1.04, 1]}
            />
          </group>
          <mesh
            name="WallShelf1 2"
            geometry={nodes['WallShelf1 2'].geometry}
            material={materials.WallShelfToon}
            castShadow
            receiveShadow
            position={[41.27, 35.39, -153.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1.16, 1]}
          />
          <mesh
            name="WallShelf1"
            geometry={nodes.WallShelf1.geometry}
            material={materials.WallShelfToon}
            castShadow
            receiveShadow
            position={[-176.86, -5.21, -153.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1.16, 1]}
          />
          <group
            name="Switch Container"
            position={[-198.96, 19.23, -158.28]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.98}
          >
            <group
              name="SwitchFinal"
              position={[-3.62, 0.8, -0.43]}
              rotation={[-2.09, -1.34, -2.08]}
              scale={[0.19, 0.19, 0.26]}
            >
              <mesh
                name="Kickstand"
                geometry={nodes.Kickstand.geometry}
                material={materials.SwitchGreyToon}
                castShadow
                receiveShadow
                position={[54.68, -62.34, -19.97]}
                rotation={[-2.77, 0, -Math.PI]}
                scale={1}
              />
              <mesh
                name="Ellipse 9"
                geometry={nodes['Ellipse 9'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[178.24, -41.74, 6.41]}
              />
              <mesh
                name="Ellipse 8"
                geometry={nodes['Ellipse 8'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[188.26, -6.69, 6.41]}
              />
              <mesh
                name="Ellipse 7"
                geometry={nodes['Ellipse 7'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[203.01, 45.16, 6.41]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[1, 1.07, 1]}
              />
              <mesh
                name="Ellipse 6"
                geometry={nodes['Ellipse 6'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[188.15, 31.27, 6.41]}
              />
              <mesh
                name="Ellipse 71"
                geometry={nodes['Ellipse 71'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[173.3, 45.16, 6.41]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[1, 1.07, 1]}
              />
              <mesh
                name="Ellipse 5"
                geometry={nodes['Ellipse 5'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[188.15, 59.04, 6.41]}
              />
              <mesh
                name="Boolean 4"
                geometry={nodes['Boolean 4'].geometry}
                material={nodes['Boolean 4'].material}
                castShadow
                receiveShadow
                position={[169.9, 73.61, 6.91]}
              />
              <mesh
                name="Rectangle 35"
                geometry={nodes['Rectangle 35'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[-176.6, -41.89, 6.41]}
              />
              <mesh
                name="Ellipse 4"
                geometry={nodes['Ellipse 4'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[-173.84, -6.04, 6.41]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[1, 1.07, 1]}
              />
              <mesh
                name="Ellipse 32"
                geometry={nodes['Ellipse 32'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[-188.6, -19.89, 6.41]}
              />
              <mesh
                name="Ellipse 41"
                geometry={nodes['Ellipse 41'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[-203.36, -6.04, 6.41]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[1, 1.07, 1]}
              />
              <mesh
                name="Ellipse 21"
                geometry={nodes['Ellipse 21'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[-188.6, 7.82, 6.41]}
              />
              <mesh
                name="Ellipse6"
                geometry={nodes.Ellipse6.geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[-188.58, 45.16, 6.41]}
              />
              <mesh
                name="Rectangle 212"
                geometry={nodes['Rectangle 212'].geometry}
                material={materials.BlackToon}
                castShadow
                receiveShadow
                position={[-167.6, 73.11, 6.41]}
              />
              <mesh
                name="Boolean 3"
                geometry={nodes['Boolean 3'].geometry}
                material={nodes['Boolean 3'].material}
                castShadow
                receiveShadow
                position={[204.39, 68.16, -0.89]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={1}
              />
              <mesh
                name="Boolean 23"
                geometry={nodes['Boolean 23'].geometry}
                material={nodes['Boolean 23'].material}
                castShadow
                receiveShadow
                position={[-204.39, 68.16, -0.89]}
              />
              <mesh
                name="RedSwitch"
                geometry={nodes.RedSwitch.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[190.21, -1.4, -8.39]}
              />
              <mesh
                name="BlueSwitch"
                geometry={nodes.BlueSwitch.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[-190.21, -1.4, 6.61]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={1}
              />
              <mesh
                name="Rectangle 42"
                geometry={nodes['Rectangle 42'].geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[-0.1, -1.89, -5.73]}
              />
              <mesh
                name="Rectangle2"
                geometry={nodes.Rectangle2.geometry}
                material={materials['']}
                castShadow
                receiveShadow
                position={[-0.1, -1.89, -8.41]}
              />
            </group>
          </group>
          <mesh
            name="Boolean4"
            geometry={nodes.Boolean4.geometry}
            material={nodes.Boolean4.material}
            castShadow
            receiveShadow
            position={[-49.07, 141.41, 49.25]}
          />
          <group name="Cupboard" position={[-169.98, -146.44, -149.1]} rotation={[0, Math.PI / 2, 0]}>
            <mesh
              name="Boolean 24"
              geometry={nodes['Boolean 24'].geometry}
              material={nodes['Boolean 24'].material}
              castShadow
              receiveShadow
              position={[0, -3.92, 0]}
            />
            <mesh
              name="Cube 10"
              geometry={nodes['Cube 10'].geometry}
              material={materials.DrawerToon}
              castShadow
              receiveShadow
              position={[-2.92, -19.96, 29.08]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.02, 1.07, 1.37]}
            />
            <mesh
              name="Cube 12"
              geometry={nodes['Cube 12'].geometry}
              material={materials.DrawerHandleToon}
              castShadow
              receiveShadow
              position={[-24.07, -19.96, 30.29]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.02, 1.07, 1.37]}
            />
            <mesh
              name="Cube 11"
              geometry={nodes['Cube 11'].geometry}
              material={materials.DrawerHandleToon}
              castShadow
              receiveShadow
              position={[-24.07, -19.96, -28.6]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.02, 1.07, 1.37]}
            />
            <mesh
              name="Cube 15"
              geometry={nodes['Cube 15'].geometry}
              material={materials.TowelsToon}
              castShadow
              receiveShadow
              position={[-0.32, 7.9, 26.82]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.02, 1.07, 1.37]}
            />
            <mesh
              name="Cube 14"
              geometry={nodes['Cube 14'].geometry}
              material={materials.TowelsToon}
              castShadow
              receiveShadow
              position={[-0.32, 7.9, -25.62]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.02, 1.07, 1.37]}
            />
            <mesh
              name="Cube 151"
              geometry={nodes['Cube 151'].geometry}
              material={materials.TowelsToon}
              castShadow
              receiveShadow
              position={[-0.32, 1.74, 26.82]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.02, 1.07, 1.37]}
            />
            <mesh
              name="Cube 13"
              geometry={nodes['Cube 13'].geometry}
              material={materials.TowelsToon}
              castShadow
              receiveShadow
              position={[-0.32, 1.74, -25.62]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.02, 1.07, 1.37]}
            />
            <mesh
              name="Cube 9"
              geometry={nodes['Cube 9'].geometry}
              material={materials.DrawerToon}
              castShadow
              receiveShadow
              position={[-2.92, -19.96, -28.6]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.02, 1.07, 1.37]}
            />
            <mesh
              name="Cube 79"
              geometry={nodes['Cube 79'].geometry}
              material={materials.DrawerToon}
              castShadow
              receiveShadow
              position={[0, 27.62, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.07, 1.07, 1]}
            />
          </group>
          <group name="Bed" position={[41.53, -127.43, -101.46]} rotation={[0, -Math.PI / 2, 0]}>
            <group name="Pillow2Container" position={[37.01, 21.77, -83.03]} rotation={[0, -0.13, 0]}>
              <mesh
                name="Pillow2"
                geometry={nodes.Pillow2.geometry}
                material={materials.Pillow2Toon}
                castShadow
                receiveShadow
                position={[0.12, -0.96, -0.75]}
                rotation={[-0.91, -0.09, -0.19]}
                scale={[0.46, 0.71, 1.45]}
              />
            </group>
            <group name="Pillow1Container" position={[-33.45, 23.68, -84.67]}>
              <mesh
                name="Pillow1"
                geometry={nodes.Pillow1.geometry}
                material={materials.PillowToon}
                castShadow
                receiveShadow
                position={[-0.14, -0.91, -0.81]}
                rotation={[-0.84, 0.12, 0.24]}
                scale={[0.43, 0.71, 1.45]}
              />
            </group>
            <mesh
              name="Cube 610"
              geometry={nodes['Cube 610'].geometry}
              material={materials['Cube 610 Material']}
              castShadow
              receiveShadow
              position={[0, 10.22, 85.58]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.03, 1, 1.45]}
            />
            <mesh
              name="Cube 22"
              geometry={nodes['Cube 22'].geometry}
              material={materials.BedMattressToon}
              castShadow
              receiveShadow
              position={[0, -13.63, 0.1]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.03, 1, 1.45]}
            />
            <mesh
              name="Cube 54"
              geometry={nodes['Cube 54'].geometry}
              material={materials.BedToon}
              castShadow
              receiveShadow
              position={[0, 21.12, 123.42]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1, 1.16, 1]}
            />
            <mesh
              name="Cube 44"
              geometry={nodes['Cube 44'].geometry}
              material={materials.BedToon}
              castShadow
              receiveShadow
              position={[0, 42.54, -123.42]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1, 1.16, 1]}
            />
            <mesh
              name="Cube 55"
              geometry={nodes['Cube 55'].geometry}
              material={materials.BedToon}
              castShadow
              receiveShadow
              position={[0, -18.7, 123.42]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube 33"
              geometry={nodes['Cube 33'].geometry}
              material={materials.BedToon}
              castShadow
              receiveShadow
              position={[0, -7.57, -123.42]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              name="Cube4"
              geometry={nodes.Cube4.geometry}
              material={materials.BedToon}
              castShadow
              receiveShadow
              position={[0, -40.77, 0.1]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <mesh
            name="Carpet"
            geometry={nodes.Carpet.geometry}
            material={materials['Carpet Material']}
            castShadow
            receiveShadow
            position={[-9.38, -176.63, 137.67]}
            scale={[0.82, 0.74, 0.82]}
          />
          <group name="Chair" position={[4.81, -143.3, 140.7]} scale={[0.82, 0.74, 0.82]}>
            <mesh
              name="Cube 56"
              geometry={nodes['Cube 56'].geometry}
              material={materials.ChairToon}
              castShadow
              receiveShadow
              position={[-16.92, -4.55, 15.9]}
              rotation={[-1.63, 0.06, -2.35]}
              scale={1}
            />
            <mesh
              name="Cube 45"
              geometry={nodes['Cube 45'].geometry}
              material={materials.ChairToon}
              castShadow
              receiveShadow
              position={[16.13, -4.55, 15.9]}
              rotation={[-1.63, -0.06, -0.79]}
              scale={1}
            />
            <mesh
              name="Cube 57"
              geometry={nodes['Cube 57'].geometry}
              material={materials.ChairToon}
              castShadow
              receiveShadow
              position={[16.13, -4.55, -17.15]}
              rotation={[-1.51, -0.06, -2.35]}
            />
            <mesh
              name="Cube 34"
              geometry={nodes['Cube 34'].geometry}
              material={materials.ChairToon}
              castShadow
              receiveShadow
              position={[-16.92, -4.55, -17.15]}
              rotation={[-1.51, 0.06, -0.79]}
              scale={1}
            />
            <mesh
              name="Cylinder 21"
              geometry={nodes['Cylinder 21'].geometry}
              material={materials['Cylinder 21 Material']}
              castShadow
              receiveShadow
              position={[0, 49.71, 0]}
            />
            <mesh
              name="Cylinder4"
              geometry={nodes.Cylinder4.geometry}
              material={materials.ChairToon}
              castShadow
              receiveShadow
              position={[0, 33.81, 0]}
            />
          </group>
          <group name="Table" position={[117.88, -132.51, 121.13]}>
            <mesh
              name="Cylinder 41"
              geometry={nodes['Cylinder 41'].geometry}
              material={materials.TableToon}
              castShadow
              receiveShadow
              position={[43.06, -2.31, 129.92]}
            />
            <mesh
              name="Cylinder 32"
              geometry={nodes['Cylinder 32'].geometry}
              material={materials.TableToon}
              castShadow
              receiveShadow
              position={[43.06, -2.31, -115.14]}
            />
            <mesh
              name="Cylinder 42"
              geometry={nodes['Cylinder 42'].geometry}
              material={materials.TableToon}
              castShadow
              receiveShadow
              position={[-41.17, -2.31, 129.92]}
            />
            <mesh
              name="Cylinder 22"
              geometry={nodes['Cylinder 22'].geometry}
              material={materials.TableToon}
              castShadow
              receiveShadow
              position={[-41.17, -2.31, -115.14]}
            />
            <mesh
              name="Rectangle 43"
              geometry={nodes['Rectangle 43'].geometry}
              material={materials.TableToon}
              castShadow
              receiveShadow
              position={[0, 31.81, 12.06]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="Walls and Floor" position={[0, -22.5, 0]}>
            <mesh
              name="Boolean5"
              geometry={nodes.Boolean5.geometry}
              material={nodes.Boolean5.material}
              castShadow
              receiveShadow
              position={[-49.97, 0, 50.15]}
            />
          </group>
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
